Error is thrown when body is None
Exception in streaming mode is thrown frequently:
 
 File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/tweepy/streaming.py", line 295, in _run
    raise exception
TypeError: argument 1 must be string or buffer, not None

Which I think is solved by setting self.body='' instead on self.body=None.
I'm not sure though about the reason behind this. But I can see that my streaming works again.